name: Demo testing 

on:
  push:
    branches:
      - Testing

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: growthlink

      - name: Set up Firebase environment variables
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          # Add other Firebase environment variables as needed
        run: echo "Environment variables set"
        working-directory: growthlink
  
      - name: Run tests
        run: npm test
        working-directory: growthlink
